name: Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ACR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}


    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: mywebappnode
        images: myacrnode.azurecr.io/myapp:latest
